In [5]:
import numpy as np

In [6]:
lst = list(range(1, 25))
arr = np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [7]:
arr2 = np.array([1,2,3 ,4 ])

In [8]:
# arange() - used to create the array 
arr=  np.arange(1, 25)
arr #single dimanesional array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [9]:
# creating 2d array 
arr = np.array([[1,2,3],[4, 5, 6,]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#2d array
arr= np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# Define dimensions of the 3D array
x, y, z = 3, 3, 3  # 3x3x3 array

# Create a 3D array with random integers
array_3d = np.random.randint(1, 100, (x, y, z))

# Print the 3D array
print("3D Array:")
print(array_3d)

3D Array:
[[[90 33 12]
  [ 2 70 48]
  [95  2 17]]

 [[26 50 58]
  [21 58 48]
  [46 77 71]]

 [[47 81  6]
  [22 84 52]
  [17 53 83]]]


In [12]:
# Create a simple 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
                      )
print("3D Array:")
print(array_3d)

3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
# Create a simple 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                      [[19, 20, 21], [22, 23, 24], [25, 26, 27]]] )
print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [14]:
#2d array
arr= np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr= np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
arr= np.linspace([1,10,3],[1,10,3])
arr

array([[ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.,  3.],
       [ 1., 10.

In [17]:
#basically reshape is use to create the create the 2D and 3d array 
# linspace is use to divide the given interval in equal space 
#it provide the floting values
arr= np.linspace(1,10,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [18]:
arr=  np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr=  np.arange(1, 31).reshape(10,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [20]:
arr=  np.arange(1, 31).reshape(3,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [21]:
#to print this function in 3d we use the one more no. in reshape 
arr= np.linspace(1,10,5).reshape(5,1,1)
arr

array([[[ 1.  ]],

       [[ 3.25]],

       [[ 5.5 ]],

       [[ 7.75]],

       [[10.  ]]])

In [22]:
#to print this function in 3d we use the one more no. in reshape 
arr=  np.arange(1, 31).reshape(3,5,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [23]:
#use to convert it into 3d in which 6rows and 1 column 
arr.reshape(5,6,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16],
        [17],
        [18]],

       [[19],
        [20],
        [21],
        [22],
        [23],
        [24]],

       [[25],
        [26],
        [27],
        [28],
        [29],
        [30]]])

In [24]:
#use to convert it into 3d 
arr.reshape(3,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [25]:
# to print it into 1d
arr= np.random.randint(1,5,9)
arr

array([3, 1, 1, 1, 3, 2, 2, 4, 1], dtype=int32)

In [26]:
#to print it into 2d
arr= np.random.randint(1,5,(3,3))
arr

array([[2, 2, 3],
       [3, 2, 3],
       [1, 2, 4]], dtype=int32)

In [27]:
#to print it into 3d
arr= np.random.randint(1,5,(3,3,3))
arr

array([[[1, 1, 4],
        [2, 3, 1],
        [3, 4, 1]],

       [[4, 2, 3],
        [4, 1, 3],
        [2, 3, 2]],

       [[2, 1, 1],
        [1, 3, 3],
        [2, 4, 2]]], dtype=int32)

In [28]:
arr= np.random.random(10)
arr

array([0.04085188, 0.30098058, 0.94156761, 0.88104399, 0.28467333,
       0.30729656, 0.19514056, 0.39057263, 0.37935672, 0.10691037])

In [29]:
#random is use to print any random value from 1to 9
arr= np.random.randint(10)
arr

4

In [30]:
arr= np.random.randint(10, size= (3,3))
arr

array([[1, 9, 6],
       [9, 5, 0],
       [3, 4, 2]], dtype=int32)

In [31]:
arr= np.random.randint(10, size= (3,3,3))
arr

array([[[4, 5, 0],
        [6, 4, 7],
        [7, 9, 2]],

       [[0, 9, 5],
        [9, 7, 5],
        [9, 4, 3]],

       [[9, 7, 3],
        [3, 0, 0],
        [9, 7, 4]]], dtype=int32)

In [32]:
#to print it in 2d
arr= np.random.random((10,5))
arr


array([[0.14658392, 0.55326574, 0.74377195, 0.47772617, 0.38419534],
       [0.73482568, 0.9197189 , 0.14934013, 0.46021713, 0.85381514],
       [0.54585012, 0.18125644, 0.25999725, 0.31583794, 0.22523086],
       [0.15177732, 0.47757876, 0.38344798, 0.59244498, 0.70075694],
       [0.1367633 , 0.27104408, 0.87763667, 0.62130565, 0.35280988],
       [0.47590267, 0.9448701 , 0.2551457 , 0.17830459, 0.86739338],
       [0.45617225, 0.47510633, 0.07413017, 0.08765862, 0.70062846],
       [0.44278126, 0.34208316, 0.02038939, 0.46359343, 0.29912106],
       [0.20590461, 0.39540846, 0.45181081, 0.54576951, 0.43201565],
       [0.89667474, 0.433569  , 0.94932271, 0.23165769, 0.4161139 ]])

In [33]:
#to check th e type of 
arr= np.arange(60).reshape(10, 6)
arr.dtype #to check the data typee
arr.ndim # to check the dimension
arr.size # to check the size of array
arr.shape # to check the shape of array

(10, 6)

In [34]:
#to check th e type of 
arr= np.arange(60).reshape(10, 6)
arr.dtype #to check the data typee
arr.ndim # to check the dimension
arr.size # to check the size of array
arr.shape # to check the shape of array
print(arr.dtype, arr.ndim, arr.size , arr.shape)

int64 2 60 (10, 6)


In [35]:
#use to convert it in 1D
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [36]:
# to check int into 1D
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [37]:

lst = list(range(1, 25))
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [38]:
#to check the shape of array
arr.shape

(24,)

In [39]:
#use to trnsform the array
arr.T.shape

(24,)

In [40]:

#to use the shape of array 
lst=[[1,2,3],[4,5,6]]
arr= np.array(lst)
arr.shape


(2, 3)

In [41]:
#use to transform the any array
arr.T.shape

(3, 2)

In [42]:
#to print the transform
lst = list(range(1, 25))
arr = np.array(lst)
arr.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [44]:
arr=np.array([1,2,3])

In [45]:
arr

array([1, 2, 3])

In [47]:
arr=np.zeros((2,3))

In [48]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
arr=np.ones(10)

In [50]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
arr.reshape(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
arr=np.random.randint(1,5,9)

In [54]:
arr

array([4, 4, 1, 3, 1, 3, 3, 1, 3], dtype=int32)

In [55]:
arr=np.random.randint(1,5,(3,3))

In [56]:
arr

array([[4, 1, 1],
       [2, 3, 1],
       [3, 4, 1]], dtype=int32)